- name: "apt: haproxy"
  ansible.builtin.apt:
    name: haproxy
    update_cache: true

- name: "haproxy: replace config"
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: "haproxy: restart"
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
